### PR TITLE
Update the site of handle the Federal riding data

### PR DESCRIPTION
**Pull request by acant**
I have done  the following in this PR:
* updated the code to display Ridings instead of Wards
* added Instrgram and Linkedin to the nominee display
* added Riding geojson

I think that this all works :) But it needs to get built on Pages to confirm that I have the map working correctly.

### CODE REVIEW

**Comment by acant** [comment]
@KristinaTaylor @pnijjar I have opened this PR and I think that it is ready to merge.
I am not sure how the CI is setup, will Travis build this PR?

**Comment by pnijjar** [comment]
I have not looked at the PR itself. But no, Jenkins (or Github pages) will not build this, I am thinking. My workflow has been to clone the repo to my own account, push into master there, and then check the results on the autobuilt page. If the changes look okay on my repo, then create the PR in the civictechwr account and pull directly. 

Do you want me to pull blindly? Or do you want to test things out on your own copy of the repo first?

**Comment by KristinaTaylor** [comment]
I'm ok with it being pulled blindly - we don't have anything pointing at this version of the repo yet, so we have an opportunity to QA before redirecting the domain.

**Comment by pnijjar** [comment]
Okay. Merging. I will probably show up tonight to follow up on this.

**Pull request merged**
